export const userRows = [
  {
    id: 1,
    firstName: "Abdelrahman",
    lastName: "Elhlew",
    ssn: 36784523661010,
    phone: "01134567893",
    city: "Zagazig",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 2,
    firstName: "Izzat",
    lastName: "Elmahlawey",
    ssn: 36082523461010,
    phone: "01234567892",
    city: "Belbies",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 3,
    firstName: "Mohamed",
    lastName: "Mahmoud",
    ssn: 36082555461010,
    phone: "01234567890",
    city: "Cairo",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 4,
    firstName: "Mohamed",
    lastName: "Ashraf",
    ssn: 36082523461010,
    phone: "01234567898",
    city: "Belbies",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 5,
    firstName: "Mahmoud",
    lastName: "Abdellah",
    ssn: 36082523461010,
    phone: "01034567895",
    city: "Belbies",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 6,
    firstName: "Mohamed",
    lastName: "Ibrahim",
    ssn: 36082523461010,
    phone: "01234567891",
    city: "Minya",
    gender: "male",
    zipCode: 44511,
  },
  {
    id: 7,
    firstName: "Menna",
    lastName: "Darwish",
    ssn: 36082523461010,
    phone: "01234567490",
    city: "Minya",
    gender: "female",
    zipCode: 44511,
  },
];
export const medicineRows = [
  {
    id: 1,
    medicine: "Panadol",
    company: "GlaxoSmithKline",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 2,
    medicine: "Voltaren",
    company: "Novartis",
    admin: "Topical",
    description: "Gel",
  },
  {
    id: 3,
    medicine: "Nexium",
    company: "AstraZeneca",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 4,
    medicine: "Advil",
    company: "Pfizer",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 5,
    medicine: "Tylenol",
    company: "Johnson & Johnson",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 6,
    medicine: "Lipitor",
    company: "Pfizer",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 7,
    medicine: "Crestor",
    company: "AstraZeneca",
    admin: "Oral",
    description: "Tablet",
  },
  {
    id: 8,
    medicine: "Singulair",
    company: "Merck & Co.",
    admin: "Oral",
    description: "Tablet",
  },
];
